config/routes.rb
Rails.application.routes.draw do

  get 'flowcharts/:id' => "welcome#diagram"

  root "welcome#index"

  resources :diagrams do
    resources :items do
      post :update_row_order, on: :collection
    end
  end

end

app/models/diagram.rb
class Diagram < ActiveRecord::Base
  has_many :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :diagram

  validates :diagram, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/diagrams_controller.rb
class DiagramsController < ApplicationController
  #Restfull service
  before_action :set_diagram, only: [:show, :edit, :update, :destroy]

  # GET /diagrams
  # GET /diagrams.json
  def index
    @diagrams = Diagram.all
  end

  # GET /diagrams/1
  # GET /diagrams/1.json
  def show
  end

  # GET /diagrams/new
  def new
    @diagram = Diagram.new
  end

  # GET /diagrams/1/edit
  def edit
  end

  # POST /diagrams
  # POST /diagrams.json
  def create
    @diagram = Diagram.new(diagram_params)

    respond_to do |format|
      if @diagram.save
        format.html { redirect_to @diagram, notice: 'Diagram was successfully created.' }
        format.json { render :show, status: :created, location: @diagram }
      else
        format.html { render :new }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagrams/1
  # PATCH/PUT /diagrams/1.json
  def update
    respond_to do |format|
      if @diagram.update(diagram_params)
        format.html { redirect_to @diagram, notice: 'Diagram was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagram }
      else
        format.html { render :edit }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagrams/1
  # DELETE /diagrams/1.json
  def destroy
    @diagram.destroy
    respond_to do |format|
      format.html { redirect_to diagrams_url, notice: 'Diagram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagram
      @diagram = Diagram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagram_params
      params.require(:diagram).permit(:name, :description)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #Restfull service
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_diagram

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    @item.diagram = @diagram

    respond_to do |format|
      if @item.save
        format.html { redirect_to [@diagram, @item], notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: [@diagram, @item] }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to [@diagram, @item], notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to diagram_item_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_diagram
      @diagram = Diagram.find(params[:diagram_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:text, :description, :name, :diagram, :diagram_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def diagram
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagrams_helper.rb
module DiagramsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/diagrams/_form.html.erb
<%= form_for(@diagram) do |f| %>
  <% if @diagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagram.errors.count, "error") %> prohibited this diagram from being saved:</h2>

      <ul>
      <% @diagram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create", :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/diagrams/edit.html.erb
<h1>Editing diagram</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagram, :class => 'btn btn-default' %>
<%= link_to 'Back', diagrams_path, :class => 'btn btn-default' %>

app/views/diagrams/index.html.erb
<h1>Listing diagrams</h1>

<div class="panel panel-default">

  <table class="table table-bordered table-striped" >
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @diagrams.each do |diagram| %>
        <tr>
          <td><%= diagram.name %></td>
          <td><%= diagram.description %></td>
          <td class="text-center"><%= link_to 'Show', diagram, :class => 'btn btn-default' %></td>
          <td class="text-center"><%= link_to 'Edit', edit_diagram_path(diagram), :class => 'btn btn-default' %></td>
          <td class="text-center"><%= link_to 'Destroy', diagram, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<%= link_to 'New Diagram', new_diagram_path, :class => 'btn btn-default' %>

app/views/diagrams/new.html.erb
<h1>New diagram</h1>

<%= render 'form' %>

<%= link_to 'Back', diagrams_path, :class => 'btn btn-default'%>

app/views/diagrams/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @diagram.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @diagram.description %>
</p>

<% @items = @diagram.items %>
<%= render template: "items/index" %>

<%= link_to 'Edit', edit_diagram_path(@diagram), :class => 'btn btn-default' %>
<%= link_to 'Back', diagrams_path, :class => 'btn btn-default' %>

app/views/items/_form.html.erb
<%= form_for [@diagram, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create", :class => 'btn btn-default'%>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', diagram_item_path( @diagram, @item), :class => 'btn btn-default' %>
<%= link_to 'Back', diagram_path(@diagram), :class => 'btn btn-default' %>

app/views/items/index.html.erb
<div class="panel panel-default">

  <table class="table table-bordered table-striped" id="sortable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Text</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr data-item-id=<%= "#{item.id}" %> class="item">
          <td><%= item.name %></td>
          <td><%= item.description %></td>
          <td><%= item.text %></td>
          <td class="text-center"><%= link_to 'Show', diagram_item_path(@diagram, item), :class => 'btn btn-default' %></td>
          <td class="text-center"><%= link_to 'Edit', edit_diagram_item_path(@diagram, item), :class => 'btn btn-default' %></td>
          <td class="text-center"><%= link_to 'Destroy', diagram_item_path(@diagram, item), method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-default'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New Item', new_diagram_item_path(@diagram), :class => 'btn btn-default' %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back',  diagram_path(@diagram), :class => 'btn btn-default' %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @item.text %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>



<%= link_to 'Edit', edit_diagram_item_path(@diagram, @item), :class => 'btn btn-default' %>
<%= link_to 'Back', diagram_path(@diagram), :class => 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>DfdAudiovisual</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<div class="container">

		<div class="row">
			<div class="col-md-12">
				<% if notice %>
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<strong>Hey!</strong> <%= notice %>
				</div>
				<% end %>

				<%= yield %>
			</div>
		</div>
	</div>


</body>
</html>

app/views/welcome/diagram.html.erb
<div id="flowchart" data-id="<%= params[:id]%>">

	
</div>

app/views/welcome/index.html.erb
<div id="flowcharts">
	
</div>